/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BaseLayout: typeof import('./src/components/BaseLayout.vue')['default']
    ClientList: typeof import('./src/components/ClientList.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElText: typeof import('element-plus/es')['ElText']
    IconAlert: typeof import('./src/components/icons/IconAlert.vue')['default']
    IconCheck: typeof import('./src/components/icons/IconCheck.vue')['default']
    IconLogout: typeof import('./src/components/icons/IconLogout.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SegmentList: typeof import('./src/components/SegmentList.vue')['default']
    TaskList: typeof import('./src/components/TaskList.vue')['default']
    TaskList2: typeof import('./src/components/TaskList2.vue')['default']
    TaskRunList: typeof import('./src/components/TaskRunList.vue')['default']
  }
}
