/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BaseLayout: typeof import('./src/components/BaseLayout.vue')['default']
    BirthdayTimeInput: typeof import('./src/components/task-time-inputs/BirthdayTimeInput.vue')['default']
    ClientForm: typeof import('./src/components/ClientForm.vue')['default']
    ClientList: typeof import('./src/components/ClientList.vue')['default']
    DailyTimeInput: typeof import('./src/components/task-time-inputs/DailyTimeInput.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElText: typeof import('element-plus/es')['ElText']
    ElTimePicker: typeof import('element-plus/es')['ElTimePicker']
    IconAlert: typeof import('./src/components/icons/IconAlert.vue')['default']
    IconCheck: typeof import('./src/components/icons/IconCheck.vue')['default']
    IconLogout: typeof import('./src/components/icons/IconLogout.vue')['default']
    LoginForm: typeof import('./src/components/LoginForm.vue')['default']
    MonthlyTimeInput: typeof import('./src/components/task-time-inputs/MonthlyTimeInput.vue')['default']
    OnesTimeInput: typeof import('./src/components/task-time-inputs/OnesTimeInput.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SegmentList: typeof import('./src/components/SegmentList.vue')['default']
    TaskForm: typeof import('./src/components/TaskForm.vue')['default']
    TaskList: typeof import('./src/components/TaskList.vue')['default']
    TaskRunList: typeof import('./src/components/TaskRunList.vue')['default']
    WeeklyTimeInput: typeof import('./src/components/task-time-inputs/WeeklyTimeInput.vue')['default']
  }
}
