name: deploy
on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # - name: Set up Node
      #   uses: actions/setup-node@v4
      #   with:
      #     node-version: 20
      #     cache: 'npm'

      # - name: Install dependencies
      #   run: npm ci

      # - name: Build
      #   run: npm run build

      # - name: Copy assets recursively to remote
      #   uses: garygrossgarten/github-action-scp@release
      #   with:
      #     local: dist/assets
      #     remote: ${{ secrets.REMOTE_PATH }}/assets
      #     host: ${{ secrets.HOST }}
      #     username: ${{ secrets.SSH_USER }}
      #     port: ${{ secrets.PORT }}
      #     privateKey: ${{ secrets.SSH_KEY}}

      - name: Copy index to remote
        uses: garygrossgarten/github-action-scp@release
        with:
          local: index.html
          # local: dist/index.html
          # remote: ${{ secrets.REMOTE_PATH }}/index.html
          # host: ${{ secrets.HOST }}
          # port: ${{ secrets.PORT }}
          # remote: ${{ secrets.REMOTE_PATH }}/index-raw.html
          remote: /home/host1869465/dijeth.ru/htdocs/www/index-raw.html
          host: serv79.hostland.ru
          username: host1869465
          port: 1024
          privateKey: ${{ secrets.SSH_KEY}}
# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepswith
# https://habr.com/ru/articles/711278/
